# Generated by Django 3.0.7 on 2020-06-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=40)),
                ('style', models.CharField(default=None, max_length=30)),
                ('year', models.DateTimeField(verbose_name='release year')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25)),
                ('origin', models.CharField(default=None, max_length=25)),
                ('band', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=40)),
                ('lyrics', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
